# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='deethon',
    version='4.3',
    description='Python3 library to easily download music from Deezer',
    project_urls={
        "documentation": "https://deethon.github.io/deethon",
        "repository": "https://github.com/StarkGangs/deethon"
    },
    author='Aykut Yilmaz',
    author_email='aykuxt@gmail.com',
    license='GPL-3.0-or-later',
    classifiers=[
        'Development Status :: 3 - Alpha', 'Operating System :: OS Independent'
    ],
    install_requires=[
        'importlib-metadata==1.*,>=1.6.0; python_version < "3.8"',
        'mutagen==1.*,>=1.44.0', 'pycryptodome==3.*,>=3.9.7',
        'requests==2.*,>=2.23.0'
    ],
)
