# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path


setup(
    name='deethon',
    version='10.3',
    description='Python3 library to easily download music from Deezer',
    project_urls={
        "documentation": "https://deethon.github.io/deethon",
        "repository": "https://github.com/StarkGangs/deethon"
    },
    author='Aykut Yilmaz',
    author_email='aykuxt@gmail.com',
    license='GPL-3.0-or-later',
    classifiers=[
        'Development Status :: 3 - Alpha', 'Operating System :: OS Independent'
    ],
    python_requires='>=3.6',
    install_requires=[
        'importlib-metadata',
        'mutagen', 'pycryptodome',
        'requests'
    ],
)
